import { Currency } from './types';

export const CURRENCIES: Currency[] = [
  { code: 'VND', name: 'Việt Nam Đồng', symbol: '₫', flag: '🇻🇳', defaultRate: 1 },
  { code: 'CNY', name: 'Nhân dân tệ', symbol: '¥', flag: '🇨🇳', defaultRate: 3520 },
  { code: 'USD', name: 'Đô la Mỹ', symbol: '$', flag: '🇺🇸', defaultRate: 25450 },
  { code: 'EUR', name: 'Euro', symbol: '€', flag: '🇪🇺', defaultRate: 27500 },
  { code: 'JPY', name: 'Yên Nhật', symbol: '¥', flag: '🇯🇵', defaultRate: 164 },
  { code: 'KRW', name: 'Won Hàn', symbol: '₩', flag: '🇰🇷', defaultRate: 18 },
  { code: 'RUB', name: 'Rúp Nga', symbol: '₽', flag: '🇷🇺', defaultRate: 275 },
  { code: 'THB', name: 'Bạt Thái', symbol: '฿', flag: '🇹🇭', defaultRate: 695 },
  { code: 'LAK', name: 'Kíp Lào', symbol: '₭', flag: '🇱🇦', defaultRate: 1.15 },
  { code: 'TWD', name: 'Đô Đài Loan', symbol: 'NT$', flag: '🇹🇼', defaultRate: 785 },
  { code: 'SGD', name: 'Đô Singapore', symbol: 'S$', flag: '🇸🇬', defaultRate: 18850 },
  { code: 'GBP', name: 'Bảng Anh', symbol: '£', flag: '🇬🇧', defaultRate: 32400 },
  { code: 'AUD', name: 'Đô Úc', symbol: 'A$', flag: '🇦🇺', defaultRate: 16750 },
  { code: 'CAD', name: 'Đô Canada', symbol: 'C$', flag: '🇨🇦', defaultRate: 18550 },
  { code: 'HKD', name: 'Đô Hồng Kông', symbol: 'HK$', flag: '🇭🇰', defaultRate: 3260 },
  { code: 'MYR', name: 'Ringgit Mã', symbol: 'RM', flag: '🇲🇾', defaultRate: 5380 },
  { code: 'CHF', name: 'Franc Thụy Sĩ', symbol: 'Fr', flag: '🇨🇭', defaultRate: 28500 },
  { code: 'NZD', name: 'Đô New Zealand', symbol: 'NZ$', flag: '🇳🇿', defaultRate: 15400 },
  { code: 'INR', name: 'Rupee Ấn Độ', symbol: '₹', flag: '🇮🇳', defaultRate: 305 },
  { code: 'BRL', name: 'Real Brazil', symbol: 'R$', flag: '🇧🇷', defaultRate: 4950 },
  { code: 'ZAR', name: 'Rand Nam Phi', symbol: 'R', flag: '🇿🇦', defaultRate: 1380 },
  { code: 'TRY', name: 'Lira Thổ Nhĩ Kỳ', symbol: '₺', flag: '🇹🇷', defaultRate: 785 },
  { code: 'MXN', name: 'Peso Mexico', symbol: '$', flag: '🇲🇽', defaultRate: 1480 },
  { code: 'IDR', name: 'Rupiah Indo', symbol: 'Rp', flag: '🇮🇩', defaultRate: 1.6 },
  { code: 'PHP', name: 'Peso Philippines', symbol: '₱', flag: '🇵🇭', defaultRate: 440 },
  { code: 'DKK', name: 'Krone Đan Mạch', symbol: 'kr', flag: '🇩🇰', defaultRate: 3680 },
  { code: 'NOK', name: 'Krone Na Uy', symbol: 'kr', flag: '🇳🇴', defaultRate: 2380 },
  { code: 'SEK', name: 'Krona Thụy Điển', symbol: 'kr', flag: '🇸🇪', defaultRate: 2420 },
  { code: 'AED', name: 'Dirham UAE', symbol: 'د.إ', flag: '🇦🇪', defaultRate: 6930 },
  { code: 'SAR', name: 'Riyal Ả Rập Xê Út', symbol: '﷼', flag: '🇸🇦', defaultRate: 6780 },
  { code: 'KWD', name: 'Dinar Kuwait', symbol: 'د.ك', flag: '🇰🇼', defaultRate: 82900 },
];
