import { Currency } from './types';

export const CURRENCIES: Currency[] = [
  { code: 'VND', name: 'Việt Nam Đồng', symbol: '₫', flag: '🇻🇳', defaultRate: 1 },
  { code: 'CNY', name: 'Nhân dân tệ', symbol: '¥', flag: '🇨🇳', defaultRate: 3520 },
  { code: 'USD', name: 'Đô la Mỹ', symbol: '$', flag: '🇺🇸', defaultRate: 25450 },
  { code: 'EUR', name: 'Euro', symbol: '€', flag: '🇪🇺', defaultRate: 27500 },
  { code: 'JPY', name: 'Yên Nhật', symbol: '¥', flag: '🇯🇵', defaultRate: 164 },
  { code: 'KRW', name: 'Won Hàn', symbol: '₩', flag: '🇰🇷', defaultRate: 18 },
  { code: 'RUB', name: 'Rúp Nga', symbol: '₽', flag: '🇷🇺', defaultRate: 275 },
  { code: 'THB', name: 'Bạt Thái', symbol: '฿', flag: '🇹🇭', defaultRate: 695 },
  { code: 'LAK', name: 'Kíp Lào', symbol: '₭', flag: '🇱🇦', defaultRate: 1.15 },
  { code: 'TWD', name: 'Đô Đài Loan', symbol: 'NT$', flag: '🇹🇼', defaultRate: 785 },
  { code: 'SGD', name: 'Đô Singapore', symbol: 'S$', flag: '🇸🇬', defaultRate: 18850 },
  { code: 'GBP', name: 'Bảng Anh', symbol: '£', flag: '🇬🇧', defaultRate: 32400 },
  { code: 'AUD', name: 'Đô Úc', symbol: 'A$', flag: '🇦🇺', defaultRate: 16750 },
  { code: 'CAD', name: 'Đô Canada', symbol: 'C$', flag: '🇨🇦', defaultRate: 18550 },
  { code: 'HKD', name: 'Đô Hồng Kông', symbol: 'HK$', flag: '🇭🇰', defaultRate: 3260 },
  { code: 'MYR', name: 'Ringgit Mã', symbol: 'RM', flag: '🇲🇾', defaultRate: 5380 },
  { code: 'CHF', name: 'Franc Thụy Sĩ', symbol: 'Fr', flag: '🇨🇭', defaultRate: 28500 },
  { code: 'NZD', name: 'Đô New Zealand', symbol: 'NZ$', flag: '🇳🇿', defaultRate: 15400 },
  { code: 'INR', name: 'Rupee Ấn Độ', symbol: '₹', flag: '🇮🇳', defaultRate: 305 },
  { code: 'BRL', name: 'Real Brazil', symbol: 'R$', flag: '🇧🇷', defaultRate: 4950 },
  { code: 'ZAR', name: 'Rand Nam Phi', symbol: 'R', flag: '🇿🇦', defaultRate: 1380 },
  { code: 'TRY', name: 'Lira Thổ Nhĩ Kỳ', symbol: '₺', flag: '🇹🇷', defaultRate: 785 },
  { code: 'MXN', name: 'Peso Mexico', symbol: '$', flag: '🇲🇽', defaultRate: 1480 },
  { code: 'IDR', name: 'Rupiah Indo', symbol: 'Rp', flag: '🇮🇩', defaultRate: 1.6 },
  { code: 'PHP', name: 'Peso Philippines', symbol: '₱', flag: '🇵🇭', defaultRate: 440 },
  { code: 'DKK', name: 'Krone Đan Mạch', symbol: 'kr', flag: '🇩🇰', defaultRate: 3680 },
  { code: 'NOK', name: 'Krone Na Uy', symbol: 'kr', flag: '🇳🇴', defaultRate: 2380 },
  { code: 'SEK', name: 'Krona Thụy Điển', symbol: 'kr', flag: '🇸🇪', defaultRate: 2420 },
  { code: 'AED', name: 'Dirham UAE', symbol: 'د.إ', flag: '🇦🇪', defaultRate: 6930 },
  { code: 'SAR', name: 'Riyal Ả Rập Xê Út', symbol: '﷼', flag: '🇸🇦', defaultRate: 6780 },
  { code: 'KWD', name: 'Dinar Kuwait', symbol: 'د.ك', flag: '🇰🇼', defaultRate: 82900 },
  { code: 'QAR', name: 'Riyal Qatar', symbol: 'ر.ق', flag: '🇶🇦', defaultRate: 7000 },
  { code: 'EGP', name: 'Bảng Ai Cập', symbol: 'E£', flag: '🇪🇬', defaultRate: 530 },
  { code: 'ILS', name: 'Shekel Israel', symbol: '₪', flag: '🇮🇱', defaultRate: 6850 },
  { code: 'PLN', name: 'Zloty Ba Lan', symbol: 'zł', flag: '🇵🇱', defaultRate: 6350 },
  { code: 'HUF', name: 'Forint Hungary', symbol: 'Ft', flag: '🇭🇺', defaultRate: 70 },
  { code: 'CZK', name: 'Koruna Séc', symbol: 'Kč', flag: '🇨🇿', defaultRate: 1100 },
  { code: 'CLP', name: 'Peso Chile', symbol: '$', flag: '🇨🇱', defaultRate: 27 },
  { code: 'COP', name: 'Peso Colombia', symbol: '$', flag: '🇨🇴', defaultRate: 6.5 },
  { code: 'PEN', name: 'Sol Peru', symbol: 'S/.', flag: '🇵🇪', defaultRate: 6800 },
  { code: 'ARS', name: 'Peso Argentina', symbol: '$', flag: '🇦🇷', defaultRate: 28 },
  { code: 'VUV', name: 'Vatu Vanuatu', symbol: 'VT', flag: '🇻🇺', defaultRate: 212 },
  { code: 'KHR', name: 'Riel Campuchia', symbol: '៛', flag: '🇰🇭', defaultRate: 6.2 },
  { code: 'MMK', name: 'Kyat Myanmar', symbol: 'Ks', flag: '🇲🇲', defaultRate: 12 },
  { code: 'MNT', name: 'Tugrik Mông Cổ', symbol: '₮', flag: '🇲🇳', defaultRate: 7.4 },
  { code: 'PKR', name: 'Rupee Pakistan', symbol: '₨', flag: '🇵🇰', defaultRate: 91 },
  { code: 'BDT', name: 'Taka Bangladesh', symbol: '৳', flag: '🇧🇩', defaultRate: 217 },
];
